[package]
name = "github_cran_description_file_downloader"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = "0.6.3"
log = "0.4.26"
reqwest = "0.12.12"
scraper = "0.23.1"
tokio = { version = "1.43.0", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
